# Uncomment the next line to define a global platform for your project

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '26.0'

  # Pods for iosApp
  pod 'shared', :path => '../shared'
end
